name: Go
on: 
  push:
    branches:
      - "master"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Check format
      run: |
        files=$(gofmt -l `find . -name '*.go'`)
        if [[ -n ${files} ]]; then
          >&2 echo "Go fmt check failed on the following files:"
          >&2 echo ""
          >&2 echo "${files}"
          >&2 echo ""
          >&2 echo "Please run \`gofmt -w .\` to reformat code."
          exit 1
        fi

    - name: Build
      run: |
        go generate  ./...
        go build ./...

    - name: Test
      run: go test ./... -coverprofile=c.out
      env:
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

    - name: Send code coverage report
      uses: aktions/codeclimate-test-reporter@v1.2.0
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        codeclimate-test-reporter-version: latest
        command: after-build --prefix gopkg.in/auth0.v5
